---
driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
